### ISSUE TITLE
impossible to use additional vendor dirs with relative path

### ISSUE THREAD

**Issue by ktruehl** [techdivision/import-cli#1]
Hi!

Once I upgrade to 3.7.1 loading my custom modules didn't work any more. The import complained that it couldn't find the `service.xml` file any more. This is how I defined the additional vendor dirs in my custom `techdivision-import.json`:
```
  "additional-vendor-dirs": [
    {
      "vendor-dir": "app/code",
      "libraries": [
        "Client/PimCategoriesImport"
      ]
    }
  ],
```
Since we have a number of setups and the placement of the `app/code` directory is not always the same depending on the setup, I cannot specifiy an absolute directory for `vendor-dir`.

The problem is that when the `XmlFileLoader` is created in `TechDivision\Import\Cli\Configuration\LibraryLoader` on line 102
```
$customLoader = new XmlFileLoader($this->getContainer(), new FileLocator());
```
no path array is given to the `FileLocator` constructor. So necessarily all additional vendor dirs must be absolute.

At least the `FileLocator` should get the current working directory as path like this:
```
$customLoader = new XmlFileLoader($this->getContainer(), new FileLocator([getcwd()]));
```

Best and thanks,
Klaas

**Comment by wagnert** [comment]
@ktruehl Has been fixed with version 3.7.3. We've refactored the functionality to behave as like before version 3.6.* which was the version you used before, I assumed.
